# Generated by Django 4.2.5 on 2023-09-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0002_editorial_delete_biblioteca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='listaLibros',
        ),
    ]
