# Generated by Django 4.2.5 on 2023-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0003_remove_editorial_listalibros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='nombre',
            new_name='nombreSocio',
        ),
    ]
